export type CreditAction = "ai_job_search" | "job_match" | "skill_gap" | "cv_analysis" | "resume_optimization" | "cover_letter" | "application_answers" | "interview_prep" | "career_analysis" | "follow_up_suggestion" | "application";
export type CreditTransaction = { id: string; type: "FREE_CREDIT" | "PURCHASE" | "JOB_APPLICATION" | "AI_ACTION" | "REFUND" | "BONUS"; amount: number; balanceAfter: number; description: string; createdAt: string; action?: CreditAction };
export type CreditWallet = { balance: number; purchased: number; spent: number; transactions: CreditTransaction[] };
export const CREDIT_COSTS: Record<CreditAction, number> = { ai_job_search: 1, job_match: 1, skill_gap: 2, cv_analysis: 3, resume_optimization: 5, cover_letter: 3, application_answers: 2, interview_prep: 3, career_analysis: 2, follow_up_suggestion: 1, application: 10 };
export const CREDIT_LABELS: Record<CreditAction, string> = { ai_job_search: "AI job search", job_match: "Job match analysis", skill_gap: "Skill gap analysis", cv_analysis: "CV analysis", resume_optimization: "CV optimization", cover_letter: "Cover letter draft", application_answers: "Application answers", interview_prep: "Interview preparation", career_analysis: "Career analysis", follow_up_suggestion: "Follow-up suggestion", application: "Job application preparation" };
export const WALLET_KEY = "qaddemni-wallet-v1";
export const INITIAL_CREDITS = 120;
export function createWallet(): CreditWallet { return { balance: INITIAL_CREDITS, purchased: 0, spent: 0, transactions: [{ id: "welcome", type: "FREE_CREDIT", amount: INITIAL_CREDITS, balanceAfter: INITIAL_CREDITS, description: "Welcome credits", createdAt: new Date().toISOString() }] }; }
export function parseWallet(raw: string | null): CreditWallet { if (!raw) return createWallet(); try { const w = JSON.parse(raw) as CreditWallet; if (typeof w.balance === "number" && Array.isArray(w.transactions)) return w; } catch { /* restore demo wallet */ } return createWallet(); }
