import type { AIAction, Application, Job, Profile } from "@/types";
export const companies = [
  { id:"northstar",name:"Northstar Health",logo:"N",industry:"Health technology",size:"200–500 employees",about:"Making proactive healthcare more accessible through thoughtful technology." },
  { id:"linear",name:"Linear",logo:"L",industry:"Software",size:"100–250 employees",about:"Building the tools that help high-performing product teams do their best work." },
  { id:"vercel",name:"Vercel",logo:"▲",industry:"Developer tools",size:"500–1,000 employees",about:"Developing the infrastructure for the modern web." },
  { id:"meridian",name:"Meridian Labs",logo:"M",industry:"Fintech",size:"50–100 employees",about:"Giving people a clearer picture of their financial lives." },
  { id:"figma",name:"Figma",logo:"F",industry:"Design software",size:"1,000+ employees",about:"Making design accessible to everyone." },
  { id:"orbit",name:"Orbit Analytics",logo:"O",industry:"Data & analytics",size:"100–250 employees",about:"Turning complex data into confident decisions." },
  { id:"delta",name:"Delta Stack",logo:"D",industry:"Software & IT",size:"25–100 employees",about:"An Alexandria engineering studio building dependable software for growing teams.",country:"Egypt",city:"Alexandria",website:"https://example.com/delta-stack",remoteAvailable:true },
  { id:"nile",name:"Nile Digital",logo:"N",industry:"Technology",size:"100–250 employees",about:"A Cairo technology company helping local businesses modernize their operations.",country:"Egypt",city:"Cairo",website:"https://example.com/nile-digital",remoteAvailable:true },
  { id:"mesopotamia",name:"Mesopotamia Cloud",logo:"M",industry:"Cloud & software",size:"25–100 employees",about:"An Iraqi cloud services team supporting secure digital infrastructure.",country:"Iraq",city:"Baghdad",website:"https://example.com/mesopotamia-cloud",remoteAvailable:true },
];
const featuredJobs: Job[] = [
 {id:"j1",title:"Senior Product Designer",company:companies[0],location:"San Francisco, CA",mode:"Hybrid",salary:"$145k–$185k",type:"Full-time",skills:["Product design","Figma","Prototyping","Design systems"],match:96,why:["Your product design experience maps directly to the role","Strong Figma and design systems experience","Healthcare interest aligns with their mission"],missing:["Healthcare domain experience"],posted:"2 days ago",description:"Lead end-to-end product design for patient and clinician experiences. Partner closely with product and engineering to make complex healthcare workflows feel simple and human.",source:"Demo source"},
 {id:"j2",title:"Product Designer, Core",company:companies[1],location:"Remote · US",mode:"Remote",salary:"$130k–$170k",type:"Full-time",skills:["Product design","Figma","Interaction design","Systems thinking"],match:92,why:["Your workflow design work is highly relevant","Your portfolio shows strong interaction craft","Remote preference is a perfect match"],missing:["Developer tools experience"],posted:"Today",description:"Design the core workflows used by product teams every day. Shape a fast, focused experience with a small team that values craft and clarity.",source:"Demo source"},
 {id:"j3",title:"Staff Product Designer",company:companies[2],location:"Remote · Americas",mode:"Remote",salary:"$170k–$220k",type:"Full-time",skills:["Design systems","Product strategy","Figma","Mentorship"],match:88,why:["Design systems expertise matches team needs","Experience partnering across functions","Career goals point toward leadership"],missing:["Developer platform experience","Public speaking"],posted:"1 day ago",description:"Set design direction for platform experiences used by developers worldwide. Raise the quality bar and help teams ship cohesive experiences.",source:"Demo source"},
 {id:"j4",title:"Product Designer",company:companies[3],location:"New York, NY",mode:"Hybrid",salary:"$120k–$155k",type:"Full-time",skills:["Product design","User research","Figma","Fintech"],match:84,why:["Research-led approach fits their product culture","Strong visual and interaction design","Salary falls in your preferred range"],missing:["Financial products experience"],posted:"3 days ago",description:"Help shape tools that make personal finance easier to understand. Work from discovery through launch alongside a collaborative product team.",source:"Demo source"},
 {id:"j5",title:"Senior UX Designer",company:companies[4],location:"San Francisco, CA",mode:"Hybrid",salary:"$150k–$190k",type:"Full-time",skills:["UX design","Prototyping","Design systems","Facilitation"],match:81,why:["Strong facilitation and systems experience","Collaborative style is a good team fit"],missing:["Collaborative design tool experience"],posted:"5 days ago",description:"Help teams make complex creative workflows feel effortless. Collaborate with researchers, engineers, and product partners.",source:"Demo source"},
 {id:"j6",title:"UX Researcher & Designer",company:companies[5],location:"Remote · US",mode:"Remote",salary:"$125k–$160k",type:"Full-time",skills:["User research","Product design","Analytics","Figma"],match:79,why:["Your research skills support their discovery work","Comfort with ambiguity matches the team"],missing:["Data visualization","SQL"],posted:"1 week ago",description:"Bridge research and design to help customers understand their data and make informed decisions.",source:"Demo source"},
];
const moreTitles = ["Product Designer, Growth","Senior UX Designer","Design Systems Lead","Product Design Manager","UX Researcher","Product Designer, Platform","Staff UX Designer","Senior Interaction Designer","Product Designer, AI","Design Strategist","Lead Product Designer","UX Designer, Consumer","Senior Visual Designer","Product Designer, Payments","Principal Product Designer","Product Design Lead","Senior UX Researcher","Product Designer, Enterprise","Accessibility Designer","Design Program Manager","Founding Product Designer","Product Designer, Mobile","Service Designer","Product Designer, Data" ];
const moreDescriptions = ["Shape end-to-end experiences with a close-knit product team. Bring clarity to complex workflows, collaborate early with engineering, and help us make the product feel effortless.","Lead discovery and design for a growing product area. You will connect user insight, business strategy, and high-quality interaction design from first sketch to launch.","Build a cohesive experience across a suite of tools. Partner with design, product, and engineering to evolve patterns that help customers move with confidence.","Help us rethink how people work with information. Bring curiosity, strong craft, and a bias toward learning through making."];
const regionalJobs: Job[] = [
 {id:"j31",title:"Python Intern",company:companies[6],location:"Alexandria, Egypt",city:"Alexandria",country:"Egypt",governorate:"Alexandria",mode:"Hybrid",salary:"12,000 EGP / month",currency:"EGP",salaryPeriod:"monthly",type:"Internship",experienceLevel:"Entry",skills:["Python","SQL","Problem solving"],match:86,why:["Python is a stated interest","Internship level is suitable for an early-career profile","Based in your preferred city"],missing:["Commercial Python experience"],posted:"Today",description:"Join a small product engineering team and contribute to internal Python tools with mentoring and a flexible hybrid schedule.",source:"Demo source · illustrative opening",applicationMethod:"demo"},
 {id:"j32",title:"Junior Python Developer",company:companies[6],location:"Alexandria, Egypt",city:"Alexandria",country:"Egypt",governorate:"Alexandria",mode:"On-site",salary:"18,000–24,000 EGP / month",currency:"EGP",salaryPeriod:"monthly",type:"Full-time",experienceLevel:"Entry",skills:["Python","Django","REST APIs"],match:82,why:["Strong overlap with Python interests","Entry-level scope","Located in Alexandria"],missing:["Django production experience"],posted:"1 day ago",description:"Build and maintain API features alongside senior engineers. The team welcomes candidates with project experience and strong fundamentals.",source:"Demo source · illustrative opening",applicationMethod:"demo"},
 {id:"j33",title:"IT Support Technician",company:companies[7],location:"Cairo, Egypt",city:"Cairo",country:"Egypt",governorate:"Cairo",mode:"Hybrid",salary:"15,000 EGP / month",currency:"EGP",salaryPeriod:"monthly",type:"Part-time",experienceLevel:"Entry",skills:["Troubleshooting","Windows","Customer support"],match:77,why:["Practical computer maintenance is relevant","Part-time schedule available","Training is provided"],missing:["Enterprise support tools"],posted:"2 days ago",description:"Help teammates resolve common device and software issues, document fixes, and learn from an experienced IT operations group.",source:"Demo source · illustrative opening",applicationMethod:"demo"},
 {id:"j34",title:"Data & Python Trainee",company:companies[7],location:"New Cairo, Egypt",city:"New Cairo",country:"Egypt",governorate:"Cairo",mode:"On-site",salary:"20,000 EGP / month",currency:"EGP",salaryPeriod:"monthly",type:"Internship",experienceLevel:"Entry",skills:["Python","Pandas","Data analysis"],match:79,why:["Python interest maps to daily tasks","Structured learning plan for junior talent"],missing:["Pandas project examples"],posted:"3 days ago",description:"A structured early-career program focused on data cleanup, Python scripts, and practical business analytics.",source:"Demo source · illustrative opening",applicationMethod:"demo"},
 {id:"j35",title:"Junior Backend Developer",company:companies[8],location:"Baghdad, Iraq",city:"Baghdad",country:"Iraq",governorate:"Baghdad",mode:"Hybrid",salary:"1,500,000 IQD / month",currency:"IQD",salaryPeriod:"monthly",type:"Full-time",experienceLevel:"Entry",skills:["Python","APIs","Linux"],match:74,why:["Python fundamentals transfer to this role","Hybrid work is available","Junior level"],missing:["Production API experience"],posted:"4 days ago",description:"Support backend feature development and learn operational practices on a small cloud product team.",source:"Demo source · illustrative opening",applicationMethod:"demo"},
 {id:"j36",title:"Remote Python Project Assistant",company:companies[8],location:"Remote · MENA",city:"Remote",country:"Multiple countries",mode:"Remote",salary:"$8–$12 / hour",currency:"USD",salaryPeriod:"hourly",type:"Part-time",experienceLevel:"Entry",skills:["Python","Documentation","Research"],match:81,why:["Remote part-time option","Python practice with clear mentorship","Flexible schedule"],missing:["Professional software delivery experience"],posted:"Today",description:"Assist a distributed engineering team with test scripts, data checks, and developer documentation on a part-time basis.",source:"Demo source · illustrative opening",applicationMethod:"demo"},
];
export const jobs: Job[] = [...featuredJobs,...moreTitles.map((title,i)=>{const company=companies[i%6];const mode=(i%3===0?"Remote":i%3===1?"Hybrid":"On-site") as Job["mode"];const city=["Remote · US","Brooklyn, NY","San Francisco, CA","Austin, TX","Seattle, WA","Boston, MA"][i%6];const skills=[["Product design","Figma","Prototyping"],["User research","Interaction design","Accessibility"],["Design systems","Product strategy","Facilitation"],["Visual design","Design systems","Figma"]][i%4];const salaryLow=112+i%7*9;const match=97-i%23;return {id:`j${i+7}`,title,company,location:city,mode,salary:`$${salaryLow}k–$${salaryLow+45}k`,type:(i%8===0?"Contract":"Full-time") as Job["type"],experienceLevel:(i%4===0?"Staff":i%3===0?"Entry":i%2===0?"Mid":"Senior") as Job["experienceLevel"],skills,match,why:[`Your ${skills[0].toLowerCase()} experience is relevant`,`Your profile aligns with ${company.name}'s team needs`,`The role supports your preference for ${mode.toLowerCase()} work`],missing:[skills[(i+1)%skills.length]],posted:["Today","1 day ago","2 days ago","4 days ago","1 week ago"][i%5],description:moreDescriptions[i%moreDescriptions.length],source:"Demo source"};}),...regionalJobs];
export const profile: Profile = { name:"",email:"",headline:"Senior Product Designer · Building thoughtful digital experiences",location:"Brooklyn, New York",about:"Product designer with 7+ years of experience turning complex problems into clear, useful experiences. I enjoy working across research, systems, and craft to help teams do their best work.",skills:["Product design","User research","Figma","Prototyping","Design systems","Interaction design","Workshop facilitation","Accessibility"],experience:[{role:"Senior Product Designer",company:"Compass Digital",period:"2022 — Present",description:"Led design for core workflow products used by 40k+ customers. Built a shared design system that improved shipping speed across 4 product teams."},{role:"Product Designer",company:"Brightside Studio",period:"2019 — 2022",description:"Designed digital experiences from early research through launch for mission-driven startups."}],education:[{degree:"BFA, Communication Design",school:"Parsons School of Design",year:"2019"}],preferredTitles:["Senior Product Designer","Product Designer","UX Designer"],preferredLocations:["Remote · US","New York, NY","San Francisco, CA"],workMode:["Remote","Hybrid"],salaryMin:130000,salaryMax:190000,employmentTypes:["Full-time"],industries:["Health technology","Developer tools","Design software"],achievements:["Improved customer onboarding completion by 18%","Built a shared design system adopted by four teams"],jobPreferences:["Product-led team","Design ownership","Mission-driven work"]};
export const applications: Application[] = [
 {id:"a1",jobId:"j1",status:"ready_for_review",updatedAt:"Today",nextStep:"Review your tailored materials"},{id:"a2",jobId:"j2",status:"submitted",updatedAt:"Yesterday",nextStep:"Waiting for employer response"},{id:"a3",jobId:"j3",status:"interview",updatedAt:"Sep 24",nextStep:"Prepare for first interview"},{id:"a4",jobId:"j4",status:"preparing",updatedAt:"Sep 23",nextStep:"Finish your cover letter"},{id:"a5",jobId:"j5",status:"saved",updatedAt:"Sep 22",nextStep:"Decide if you want to apply"},{id:"a6",jobId:"j6",status:"viewed",updatedAt:"Sep 20",nextStep:"Check in with the employer"},
];
export const activity: AIAction[] = [
 {id:"ai1",title:"Your match brief is ready",detail:"Senior Product Designer at Northstar Health · 96% match",time:"2 min ago",kind:"match",demo:true},{id:"ai2",title:"Resume tailored for review",detail:"Product Designer, Core at Linear · 3 changes suggested",time:"1 hour ago",kind:"prep",demo:true},{id:"ai3",title:"A pattern worth noticing",detail:"Your strongest matches value design systems experience",time:"Yesterday",kind:"insight",demo:true},{id:"ai4",title:"Application status updated",detail:"Vercel viewed your application",time:"Sep 25",kind:"match",demo:true},
];
