export type EmploymentType = "Full-time" | "Part-time" | "Internship" | "Freelance" | "Contract" | "Temporary";
export type WorkMode = "Remote" | "Hybrid" | "On-site";
export type ApplicationStatus = "discovered" | "saved" | "preparing" | "ready_for_review" | "submitted" | "applied" | "viewed" | "response" | "screening" | "interview" | "rejected" | "offer" | "withdrawn";
export type ApplicationMethod = "company_website" | "external_ats" | "email" | "recruiter" | "qaddemni_integration" | "save_for_later";
export interface Company { id: string; name: string; logo: string; industry: string; size: string; about: string; country?: string; city?: string; website?: string; remoteAvailable?: boolean }
export interface Job { id: string; title: string; company: Company; location: string; mode: WorkMode; salary: string; type: EmploymentType; experienceLevel?: "Entry" | "Mid" | "Senior" | "Staff"; skills: string[]; match: number; why: string[]; missing: string[]; posted: string; description: string; source: string; sourceUrl?: string; country?: string; governorate?: string; city?: string; currency?: string; salaryPeriod?: "monthly" | "annual" | "hourly"; applicationMethod?: "company_website" | "external_ats" | "email" | "recruiter" | "demo"; latitude?: number; longitude?: number }
export interface Experience { role: string; company: string; period: string; description: string }
export interface Education { degree: string; school: string; year: string }
export interface Profile { name: string; email: string; headline: string; location: string; about: string; skills: string[]; experience: Experience[]; education: Education[]; preferredTitles: string[]; preferredLocations: string[]; workMode: WorkMode[]; salaryMin: number; salaryMax: number; employmentTypes: EmploymentType[]; industries?: string[]; achievements?: string[]; jobPreferences?: string[]; phone?: string; country?: string; governorate?: string; city?: string; latitude?: number; longitude?: number; locationPermission?: "allowed" | "city_only" | "denied" | "not_requested"; studentStatus?: "student" | "working" | "between_roles" | "unsure"; cvStatus?: "has_cv" | "outdated_cv" | "no_cv" | "unsure"; commutePreference?: string; relocationPreference?: "yes" | "maybe" | "no"; currency?: string; salaryPeriod?: "monthly" | "annual" | "hourly"; languages?: string[]; certifications?: string[]; projects?: string[]; availability?: string; urgency?: string; }
export interface Preferences { emailUpdates: boolean; weeklyDigest: boolean; profileVisibility: string; theme: string }
export interface Application { id: string; jobId: string; status: ApplicationStatus; updatedAt: string; nextStep?: string; followUpDate?: string; interviewDate?: string; interviewDetails?: string; userId?: string; companyId?: string; resumeVersionId?: string; coverLetter?: string; answers?: Record<string,string>; applicationMethod?: ApplicationMethod; submittedAt?: string; externalApplicationUrl?: string; notes?: string[] }
export interface AIAction { id: string; title: string; detail: string; time: string; kind: "match" | "prep" | "insight"; demo: boolean }
export interface CareerTask { id: string; title: string; detail: string; due: string; priority: "High" | "Medium" | "Low"; complete: boolean; applicationId?: string }
export interface ApplicationNote { id: string; applicationId: string; text: string; createdAt: string }
export interface ApplicationContact { id: string; applicationId: string; name: string; role: string; email: string }
export interface ApplicationEvent { id: string; applicationId: string; label: string; detail: string; date: string }
export interface ResumeVersion { id: string; name: string; focus: string; updated: string; strength: number }
