"use client";
import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";
import { CareerAgentVisual, CareerJourney } from "@/components/career-visuals";
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Check, CircleDot, Globe2, LockKeyhole, Sparkles, Target, Workflow } from "lucide-react";
import { useLocale } from "@/lib/use-locale";

export default function Landing() { const {locale,t,setLanguage}=useLocale(); return <main className="landing-page"><nav className="landing-nav"><Link href="/" className="brand" style={{padding:0}}><BrandLogo priority/><span>Qaddemni</span><span className="brand-ar">قدّمني</span></Link><div className="landing-links"><a href="#journey">{t("How it works")}</a><a href="#principles">{t("Our approach")}</a><a href="#workspace">{t("Product")}</a></div><div style={{display:"flex",gap:9,alignItems:"center"}}><select aria-label="Language" className="language-select" value={locale} onChange={e=>setLanguage(e.target.value as "en"|"ar")}><option value="en">English</option><option value="ar">العربية</option></select><Link className="btn ghost small landing-login" href="/app">{t("Log in")}</Link><Link className="btn primary small" href="/onboarding">{t("Start your plan")} <ArrowRight size={14}/></Link></div></nav>
  <section className="hero"><div className="hero-inner"><div className="hero-kicker"><span className="pulse-dot"/> {t("YOUR CAREER, IN MOTION")}</div><h1>{t("Your next move")}<br/>{t("deserves a")} <em>{t("strategy")}</em></h1><p>{t("Tell me what you’re looking for. I’ll help you narrow it down, understand why a role fits, and prepare your next step—with you in control.")}</p><div className="hero-actions"><Link href="/onboarding" className="btn primary">{t("Build your career plan")} <ArrowRight size={15}/></Link><Link href="/app" className="btn hero-secondary">{t("Explore the product")} <ArrowUpRight size={14}/></Link></div><div className="hero-proof"><span><Check size={13}/> {t("You stay in control")}</span><span><LockKeyhole size={13}/> {t("Private by design")}</span><span><CircleDot size={13}/> {t("No automatic submissions")}</span></div><CareerAgentVisual locale={locale}/></div></section>
  <section className="landing-trust"><span>{t("CAREER CLARITY, BUILT AROUND YOU")}</span><div><span><Target size={14}/> {t("YOUR GOALS")}</span><i/><span><BriefcaseBusiness size={14}/> {t("REAL OPPORTUNITIES")}</span><i/><span><Workflow size={14}/> {t("MEANINGFUL PROGRESS")}</span></div></section>
  <section className="landing-section" id="journey"><div className="landing-section-head"><div><p className="eyebrow">{t("ONE CONNECTED JOURNEY")}</p><h2>{t("From possibility")}<br/>{t("to")} <em>{t("progress")}</em></h2></div><p>{t("Career moves take more than a polished resume and an endless list of openings. Qaddemni brings the whole process into one thoughtful workspace.")}</p></div><CareerJourney locale={locale}/></section>
  <section className="product-preview" id="workspace"><div className="preview-copy"><p className="eyebrow">{t("A CALMER WAY TO MOVE FORWARD")}</p><h2>{t("See the full picture.")}<br/><em>{t("Choose your next step.")}</em></h2><p>{t("Understand why a role fits, where you could grow, and what to do next. Your agent organizes the work; every important choice stays with you.")}</p><div className="preview-points"><span><Check size={14}/> {t("Explainable job matches")}</span><span><Check size={14}/> {t("Application prep you can edit")}</span><span><Check size={14}/> {t("Progress that teaches you")}</span></div><Link href="/app" className="text-link">{t("Explore the demo workspace")} <ArrowRight size={14}/></Link></div><div className="preview-window"><div className="preview-top"><span className="window-dots"><i/><i/><i/></span><span>QADDEMNI / OVERVIEW</span><span className="preview-avatar">AM</span></div><div className="preview-welcome"><div><span>MONDAY, SEPTEMBER 28</span><h3>Good morning, Alex.</h3><p>Here’s what’s moving your career forward.</p></div><div className="preview-credits"><Sparkles size={13}/> 120 credits</div></div><div className="preview-stats"><div><span>Strong matches</span><b>12</b><small>↑ 4 this week</small></div><div><span>In progress</span><b>4</b><small>Across 3 stages</small></div><div><span>Profile strength</span><b>82%</b><small>Improve your signal</small></div></div><div className="preview-bottom"><div className="preview-job"><span className="preview-mini-logo">N</span><div><b>Senior Product Designer</b><small>Northstar Health · Remote</small></div><strong>96%</strong></div><div className="preview-agent"><span className="agent-star"><Sparkles size={13}/></span><div><b>Your AI is working</b><small>Your role match brief is ready · DEMO</small></div><ArrowRight size={13}/></div></div></div></section>
  <section className="principles" id="principles"><div><Globe2 size={17}/><b>{t("Built for your direction")}</b><span>{t("Your definition of a good move comes first.")}</span></div><div><LockKeyhole size={17}/><b>{t("Private and considered")}</b><span>{t("Your career information is yours to control.")}</span></div><div><Sparkles size={17}/><b>{t("AI with a clear role")}</b><span>{t("Useful support, transparent suggestions.")}</span></div></section>
  <section className="landing-cta"><p className="eyebrow">{t("YOUR NEXT CHAPTER STARTS WITH CLARITY")}</p><h2>{t("Make the next move")}<br/><em>{t("feel like yours.")}</em></h2><p>{t("Start with the work you want to do. Qaddemni will help you find a practical way forward.")}</p><Link href="/onboarding" className="btn primary">{t("Build your career plan")} <ArrowRight size={14}/></Link></section>
  <footer className="landing-footer"><Link href="/" className="brand" style={{padding:0}}><BrandLogo priority/> Qaddemni <span className="brand-ar">قدّمني</span></Link><span>© 2026 Qaddemni · {t("Your career, in motion.")}</span><span>{t("AI suggests. You decide.")}</span></footer></main> }

