"use client";
import { useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, Mail, MessageCircle, Phone, ShieldCheck, Timer } from "lucide-react";
import { DemoVerificationProvider, normalizeE164, type VerificationChannel } from "@/lib/integrations/verification";

const provider=new DemoVerificationProvider();
type Pending={destination:string;code:string;expiresAt:number;retryAt:number};
const countryCodes=[["+20","Egypt +20"],["+964","Iraq +964"],["+966","Saudi Arabia +966"],["+971","UAE +971"],["+974","Qatar +974"],["+965","Kuwait +965"],["+973","Bahrain +973"],["+968","Oman +968"],["+962","Jordan +962"],["+961","Lebanon +961"],["+212","Morocco +212"],["+216","Tunisia +216"]];
export default function VerificationCenter(){const [email,setEmail]=useState("");const [countryCode,setCountryCode]=useState("+20");const [phone,setPhone]=useState("");const [pending,setPending]=useState<Partial<Record<VerificationChannel,Pending>>>({});const [codes,setCodes]=useState<Partial<Record<VerificationChannel,string>>>({});const [verified,setVerified]=useState<Partial<Record<VerificationChannel,boolean>>>({});const [error,setError]=useState("");const [notice,setNotice]=useState("");const [now,setNow]=useState(Date.now());
 useEffect(()=>{try{setVerified(JSON.parse(localStorage.getItem("qaddemni-verification-status")||"{}"))}catch{}},[]);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 const destination=(channel:VerificationChannel)=>channel==="email"?email.trim().toLowerCase():normalizeE164(countryCode,phone)||"";
 const send=async(channel:VerificationChannel)=>{setError("");setNotice("");const to=destination(channel);if(!to){setError(channel==="email"?"Enter a valid email address first.":"Enter a valid phone number and country code.");return}const result=channel==="email"?await provider.sendOTP(to):await provider.sendOTP(to,channel);if(!result.ok){setError(result.error||"Could not start demo verification.");return}setPending({...pending,[channel]:{destination:to,code:result.code!,expiresAt:result.expiresAt!,retryAt:result.retryAt!}});setCodes({...codes,[channel]:""});setNotice(channel==="whatsapp"?"Demo Mode — WhatsApp verification isn’t connected yet. No message was sent.":channel==="sms"?"Demo Mode — SMS delivery isn’t connected. No message was sent.":"Demo Mode — no email was sent. Use the temporary code shown below.")};
 const verify=async(channel:VerificationChannel)=>{const challenge=pending[channel];if(!challenge)return;const to=destination(channel);if(to!==challenge.destination){setError("The destination changed. Request a new code.");return}const result=channel==="email"?await provider.verifyOTP(to,codes[channel]||""):await provider.verifyOTP(to,channel,codes[channel]||"");if(!result.ok){setError(result.error||"Verification did not complete.");return}const next={...verified,[channel]:true};setVerified(next);localStorage.setItem("qaddemni-verification-status",JSON.stringify(next));setPending({...pending,[channel]:undefined});setError("");setNotice(`${channelLabel(channel)} verified in this demo browser.`)};
 const row=(channel:VerificationChannel,icon:React.ReactNode,label:string)=>{const challenge=pending[channel];const remaining=challenge?Math.max(0,Math.ceil((challenge.expiresAt-now)/1000)):0;const retry=challenge?Math.max(0,Math.ceil((challenge.retryAt-now)/1000)):0;return <div className="verification-row" key={channel}><div className="verification-title"><span className="verification-icon">{icon}</span><div><strong>{label}</strong><small>{verified[channel]?"Verified in this demo":"Not verified"}</small></div><span className={`status ${verified[channel]?"ready_for_review":""}`}>{verified[channel]?<><CheckCircle2 size={11}/> Verified</>:"DEMO"}</span></div>{channel==="email"?<input className="verification-input" type="email" autoComplete="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/>:<div className="verification-phone"><select className="select" value={countryCode} onChange={e=>setCountryCode(e.target.value)} aria-label="Phone country code">{countryCodes.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><input className="verification-input" type="tel" autoComplete="tel-national" placeholder="Phone number" value={phone} onChange={e=>setPhone(e.target.value)}/></div>}{!verified[channel]&&<><div className="verification-actions"><button className="btn small" onClick={()=>send(channel)} disabled={retry>0}>{challenge?(retry?`Resend in ${retry}s`:"Resend code"):channel==="email"?"Send verification code":"Send demo code"}</button>{challenge&&<span className="activity-detail"><Timer size={11}/> Expires in {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,"0")}</span>}</div>{challenge&&remaining>0&&<div className="demo-otp"><strong>Demo only</strong><span>Temporary code: <code>{challenge.code}</code></span><small>This code is held in memory for this demo session only; it was not delivered.</small></div>}{challenge&&<div className="verification-actions"><input className="verification-input otp-input" inputMode="numeric" maxLength={6} autoComplete="one-time-code" placeholder="6-digit code" value={codes[channel]||""} onChange={e=>setCodes({...codes,[channel]:e.target.value.replace(/\D/g,"").slice(0,6)})}/><button className="btn primary small" onClick={()=>verify(channel)}>Verify</button></div>}</>}</div>};
 return <section className="panel verification-center"><div className="verification-header"><div className="metric-icon"><ShieldCheck size={17}/></div><div><h3>Contact verification</h3><p>Email, SMS, and WhatsApp are demo-only here.</p></div></div>{notice&&<div className="status ready_for_review verification-notice">{notice}</div>}{error&&<div className="verification-error"><AlertCircle size={13}/>{error}</div>}{row("email",<Mail size={14}/>,"Email")}{row("sms",<Phone size={14}/>,"Phone · SMS")}{row("whatsapp",<MessageCircle size={14}/>,"WhatsApp")}</section>;
}
function channelLabel(channel:VerificationChannel){return channel==="email"?"Email":channel==="sms"?"Phone":"WhatsApp"}
